const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const model = {};
vm.createContext(model);
vm.runInContext(fs.readFileSync('Model.js', 'utf8'), model);
const repos = [{repo: 'owner/repo', runs: [{id: 7, status: 'in_progress', name: 'CI', head_branch: 'main', run_number: 3}]}];
const expanded = {'repo:owner/repo': true, 'owner/repo:7': true, 'owner/repo:7:8': true};
const details = {'owner/repo:7': {jobs: [{id: 8, name: 'build', status: 'in_progress', steps: [{number: 1, name: 'Checkout', status: 'completed', conclusion: 'success'}]}]}};
const rows = model.rows(repos, expanded, details, '', Date.now());
assert.equal(rows.length, 4);
assert.equal(rows[3].title, 'Checkout');
assert.equal(rows[3].status, 'success');
assert.equal(rows[2].info.startsWith('1/1 steps'), true);
assert.equal(model.selection(rows, 'owner/repo:7:8', 0), 2);
assert.equal(model.selection([], 'missing', 5), 0);
assert.equal(model.rows(repos, {}, details, '', Date.now()).length, 1);
assert.equal(model.rows(repos, {}, {}, 'main', Date.now()).length, 2);
assert.equal(model.rows(repos, expanded, details, 'missing', Date.now()).length, 0);
assert.equal(model.rows(repos, expanded, {}, '', Date.now())[2].title, 'Loading jobs…');
assert.equal(model.duration({started_at:'2026-01-01T00:00:00Z'}, Date.parse('2026-01-01T00:01:15Z')), '1m 15s');
assert.equal(model.icon('cancelled'), '⊘');
assert.equal(model.icon('failure'), '✕');
console.log('Model: hierarchy, filtering, progress, selection and duration passed');
